### ISSUE TITLE
When more the one airgradient installed, only one is providing data

### ISSUE THREAD

**Issue by Impatience71** [MallocArray/airgradient_esphome#1]
First of all - Thanks for your awsome integration !
When I install 2 airgradients (name is different in the config of course), the ESPHome log shows that both are working, each have different IP addresses, both deliver different values. But in Grafana only one of the sensor provides accessable data. Would it be possible that they collide somehow ?
Peter

**Comment by MallocArray** [comment]
I only have one item connected currently, so I haven't tested 2 at the same time, but I suspect it is related to the ID being the same.  On one of the devices, change the sensor IDs to have a unique name, so instead of
```yaml
id: pm2
```
change one of them to something like:
```yaml
id: pm2_basement
```
Then you'll also need to change the references in the display area to also have the new line
```yaml
     - id: display_pm2
        lambda: |-
          it.print(0, 0, id(font1), "PM2");
          it.printf(64, 24, id(font1), TextAlign::TOP_RIGHT, "%.0f",id(pm2).state);
``` 
becomes
```yaml
     - id: display_pm2
        lambda: |-
          it.print(0, 0, id(font1), "PM2");
          it.printf(64, 24, id(font1), TextAlign::TOP_RIGHT, "%.0f",id(pm2_basement).state);
```

Then push the new config in ESPHome and see if the unique values become available.
