### ISSUE TITLE
Error "ID EC:DA:3B:XX:XX:XX-sensor-pm_2_5 is already used by sensor.ag_open_air_o_1pst_pm_2_5"

### ISSUE THREAD

**Issue by Qhilm** [MallocArray/airgradient_esphome#109]
>[!NOTE]
>ESPhome: 2024.12.2
>Home Assistant: 2025.1.2
>Hardware: Open Air O 1PST

I am not sure when this started and I'm also not sure this is related to `airgradient_esphome` and not an issue with ESPhome itself.

Error:

>Logger: homeassistant.components.sensor
>Source: helpers/entity_platform.py:773
>integration: Sensor (documentation, issues)
>First occurred: 15:50:29 (1 occurrences)
>Last logged: 15:50:29
>
>Platform esphome does not generate unique IDs. ID EC:DA:3B:XX:XX:XX-sensor-pm_2_5 is already used by >sensor.ag_open_air_o_1pst_pm_2_5 - ignoring sensor.ag-open-air-o-1pst_pm_2_5

It seems like ESPhome it is indeed probably the same sensor in both cases and HA somehow identifies it as different names. It appears that some hyphens are replaced by underscores, maybe it's a parsing issue.

Does that ring a bell for anyone?

```yaml
substitutions:
  name: "ag-open-air-o-1pst"
  friendly_name: "AG Open Air O-1PST"
  name_add_mac_suffix: "false"  # Must have quotes around value

# Enable Home Assistant API
api:  # Add encryption key as desired
  encryption:
    key: !secret home_assistant_encryption_key

# web GUI not needed unless troubleshooting
# web_server:

ota:  # Add password as desired
  password: !secret ota_password
  platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  reboot_timeout: 15min
  ap:
    ssid: "${friendly_name} Hotspot"
    password: !secret fallback_ssid_password

dashboard_import:
  package_import_url: github://MallocArray/airgradient_esphome/airgradient-open-air-o-1pst.yaml
  import_full_config: false

packages:
  board: github://MallocArray/airgradient_esphome/packages/airgradient_esp32-c3_board.yaml
  # captive_portal: github://MallocArray/airgradient_esphome/packages/captive_portal.yaml
  # pm_2.5: github://MallocArray/airgradient_esphome/packages/sensor_pms5003t.yaml
  pm_2.5: github://MallocArray/airgradient_esphome/packages/sensor_pms5003t_extended_life.yaml
  co2: github://MallocArray/airgradient_esphome/packages/sensor_s8.yaml
  tvoc: github://MallocArray/airgradient_esphome/packages/sensor_sgp41.yaml
  airgradient_api: github://MallocArray/airgradient_esphome/packages/airgradient_api_esp32-c3.yaml
  hardware_watchdog: github://MallocArray/airgradient_esphome/packages/watchdog.yaml
  wifi: github://MallocArray/airgradient_esphome/packages/sensor_wifi.yaml
  uptime: github://MallocArray/airgradient_esphome/packages/sensor_uptime.yaml
```
