### ISSUE TITLE
Open Air Temperature Differential

### ISSUE THREAD

**Issue by spiceywasabi** [MallocArray/airgradient_esphome#111]
Hello,

I just flashed my AirGradient Open Air 1-PPT. This version has the two temperature sensors averaging out. I noticed the temperature average was 41 degrees F instead of 60 F. Quick look at the data shows one of the sensors is reporting F but is actually in C. Looking quickly at the full configuration it seems everything is normalized to C so I'm unsure if this is a bug here or somewhere else. 

<img width="460" alt="Image" src="https://github.com/user-attachments/assets/7ef291f7-11c8-4473-9107-70c7dab2b7f4" />

Configuration used:
```yaml
dashboard_import:
  package_import_url: github://MallocArray/airgradient_esphome/airgradient-open-air-o-1ppt.yaml
  import_full_config: 


packages:
  board: github://MallocArray/airgradient_esphome/packages/airgradient_esp32-c3_board.yaml
  captive_portal: github://MallocArray/airgradient_esphome/packages/captive_portal.yaml
  pm_2.5: github://MallocArray/airgradient_esphome/packages/sensor_pms5003t.yaml
  # pm_2.5: github://MallocArray/airgradient_esphome/packages/sensor_pms5003t_extended_life.yaml
  pm_2.5_2: github://MallocArray/airgradient_esphome/packages/sensor_pms5003t_2.yaml
  # pm_2.5_2: github://MallocArray/airgradient_esphome/packages/sensor_pms5003t_2extended_life.yaml
  tvoc: github://MallocArray/airgradient_esphome/packages/sensor_sgp41.yaml
  airgradient_api: github://MallocArray/airgradient_esphome/packages/airgradient_api_esp32-c3_dual_pms5003t.yaml
  hardware_watchdog: github://MallocArray/airgradient_esphome/packages/watchdog.yaml
  wifi: github://MallocArray/airgradient_esphome/packages/sensor_wifi.yaml
  uptime: github://MallocArray/airgradient_esphome/packages/sensor_uptime.yaml

```
