### ISSUE TITLE
Near-constant reboots on Airgradient One

### ISSUE THREAD

**Issue by amarshall** [MallocArray/airgradient_esphome#124]
Running v5.0.0, ESPHome 2025.2.2. Some time ago I tried upgrading to v4.0.7, but ultimately downgraded back to v2.0.5 because of this same issue. Reboots are so frequent (sometimes no more than every few minutes!) that it in fact becomes challenging even to flash the device, as there is often not enough time to do so before a restart. Even on v2.0.5 I didn’t have great uptime, but not *this* bad.

![uptime graph](https://github.com/user-attachments/assets/981b190f-29b2-4d2c-82fe-8340ad316dfd)

Config, with some things removed from the “default” based on suggestions from previous issues:
```yaml
# AirGradient ONE - Board v9
# https://www.airgradient.com/open-airgradient/instructions/overview/

binary_sensor:
  - id: !extend config_button
    pin:
      ignore_strapping_warning: true # Acknowledging that this is a strapping pin and should not have external pullup/down resistors  https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
mqtt:
  broker: mymqtt.example
  password: !secret mqtt-password
  reboot_timeout: 0s
  username: airgradient-01
ota:
  password: !secret ota-password
  platform: esphome
packages:
  board: !include ./packages/airgradient_esp32-c3_board.yaml
  captive_portal: !include ./packages/captive_portal.yaml
  co2: !include ./packages/sensor_s8.yaml
  config_button: !include ./packages/config_button.yaml
  display: !include ./packages/display_sh1106_multi_page.yaml
  hardware_watchdog: !include ./packages/watchdog.yaml
  led: !include ./packages/led.yaml
  led_co2: !include ./packages/led_combo.yaml
  pm_2.5: !include ./packages/sensor_pms5003.yaml
  temp_humidity: !include ./packages/sensor_sht40.yaml
  tvoc: !include ./packages/sensor_sgp41.yaml
  uptime: !include ./packages/sensor_uptime.yaml
  wifi: !include ./packages/sensor_wifi.yaml
substitutions:
  config_version: 5.0.0
  friendly_name: "airgradient-01"
  name: "airgradient-01"
  name_add_mac_suffix: "false" # Must have quotes around value
text_sensor:
  - hide_timestamp: true
    name: "ESPHome Version"
    platform: version
wifi:
  password: !secret wifi-password
  ssid: My WiFi
```
