### ISSUE TITLE
Multiple sensors  friendly entity name

### ISSUE THREAD

**Issue by Motya-HA** [MallocArray/airgradient_esphome#13]
Hello
I know that Malloc already created solution for multiple sensors with  the following line:
name_add_mac_suffix: true  # Set to false if you don't want part of the MAC address in the name

In that case entity is looking like that:
"airgradient_one_0c0acc_pm_0_3" , where "0c0acc" is a MAC address

I am wondering if there is a way to create aenetety that reflects location, for example: for "master bedroom" - "airgradient_one_master bedroom_pm_0_3", for "guest room" :"airgradient_one_guest_room_pm_0_3" etc.

Thanks

**Comment by MallocArray** [comment]
You could change the `devicename: ` field to be whatever you wanted it to be named, and if you don't want the MAC added, set that to false. Just make sure the device name is unique to all of the device in your HomeAssistant

So example would be 
```yaml
devicename: "airgradient_one_master_bedroom"
upper_devicename: "AG One Master Bedroom"
add_mac_suffix: "false"
```
