### ISSUE TITLE
No long term stats in HA with AQI?

### ISSUE THREAD

**Issue by pyrodex** [MallocArray/airgradient_esphome#139]
I noticed the other entities seem to have long term stats in my HA but I don't see this for AQI. I only have the last 3 days, my recorder settings, so not sure why this entity isn't doing long term stats.

Record settings for example:

```
recorder:
  purge_keep_days: 3
  exclude:
    domains:
      - uptime
      - time_date
      - worldclock
    entity_globs:
      - sensor.time*
      - sensor.uptime*
      - sensor.*_distance_to_*
```
