### ISSUE TITLE
Update to support breaking changes in ESPHome 2025.5.0 with HTTP requests.

### ISSUE THREAD

**Issue by pyrodex** [MallocArray/airgradient_esphome#140]
According to the release notes they made a breaking change around http request headers (https://esphome.io/changelog/2025.5.0.html#http-request)

Looks like all occurrences of `headers` will need to be replaced with `request_headers`. 

```
esphome: None
  name: ag-open-air-o-1ppt
  friendly_name: AG Open Air O-1PPT
  name_add_mac_suffix: False
  project: 
    name: mallocarray.airgradient
    version: 5.1.0
  min_version: 2025.2.0
  on_boot: 
    - priority: 200
      then: 
        if: 
          condition: 
            switch.is_on: upload_airgradient
          then: 
            - http_request.post: 
                url: !lambda |-
                  return "https://hw.airgradient.com/sensors/airgradient:" + get_mac_address() + "/measures";
                
                The 'headers' options has been renamed to 'request_headers'.
                headers: 
                  Content-Type: application/json
                json: 
                  wifi: !lambda |-
                    return to_string(-50);
  build_path: build/ag-open-air-o-1ppt
```
