### ISSUE TITLE
Thoughts about LED gauge?

### ISSUE THREAD

**Issue by joneshf** [MallocArray/airgradient_esphome#34]
Is there any interest in using the LEDs as a gauge? Right now, it seems that it uses all 11 LEDs at once, and they all have the same color (based on CO<sub>2</sub>). But using something like [light.addressable_set](https://esphome.io/components/light/#light-addressable-set-action) and [light.pulse_effect](https://esphome.io/components/light/#pulse-effect) it could also be something like:
| CO<sub>2</sub> | LEDs |
| --- | --- |
| < 800 ppm | 🟢🟢 |
| >= 800 ppm && < 1000 ppm | 🟢🟢🟢🟢 |
| >= 1000 ppm && < 1200 ppm | 🟡🟡🟡🟡🟡🟡 |
| >= 1200 ppm && < 1400 ppm | 🟡🟡🟡🟡🟡🟡🟡🟡 |
| >= 1400 ppm && < 1600 ppm | 🔴🔴🔴🔴🔴🔴🔴🔴🔴🔴 |
| > 1600 ppm | 🔴🔴🔴🔴🔴🔴🔴🔴🔴🔴 (slowly pulsing) |

Or leave the pulsing off, if that seems like too much. In any case, what do you think about something like this?

**Comment by MallocArray** [comment]
I like the idea.  Would have to see how that feels in real life, if having only 2 green seems like it isn't being utilized.

Do you want to mock up the ESPHome config to enable it and we can see how it feels?  

I would probably match the levels to what is currently defined and the color, but adjust how many LEDs are used.  AirGradient released a new version of their Arduino code that I want to see if they changed the scales at all.

I also have plans to make an option to have the LED reflect the PM2.5 levels instead of CO2 so users have options.  I toyed around with having the bar split, so left half was CO2 and right half was PM2.5 but think that may end up confusing.

**Comment by joneshf** [comment]
Okay cool. I threw something together yesterday without the pulsing (because I was lazy). Lemme change back the colors/thresholds and I'll toss it up.

Re: splitting. There's 11 LEDs. Maybe having each side be 5 LEDs with an unused one in the middle might be enough of a visual cue? Something like:
🟢🟢🟢🟢🟢⚪🟢🟢🟢🟢🟢

I actually kind of like the idea of showing two (or more) things. Might noodle around with that as well. Maybe slap a (removable) label under each section or something.

**Comment by MallocArray** [comment]
Did you have some example code to share yet?

**Comment by joneshf** [comment]
Oh also, all of the LEDs are on when first powering on the device. After the CO<sub>2</sub> is reporting and the interval has passed, the LEDs to change to this gauge. I'm not sure which thing would need to change to make it do something different.

**Comment by scynthero** [comment]
I just bought AirGradient ONE and the default firmware has something similar if not straight the same as joneshf idea. It looks really nice.

**Comment by DamonLane** [comment]
Seeing the row of LEDs, I assumed the acted like a gauge, and as scynthero mentioned, the default firmware does something like this. I didn't keep it on long enough to see what it was doing.

As a data analyst, I feel like this has to show at least two metrics, but we don't want to over-complicate it. It would seem intuitive to me if the gauge was the level of CO2 and the color was the PM. A discussion like this is good because what's intuitive is probably different for different people.

**Comment by ossgeek314** [comment]
As @scynthero has mentioned, the default AirGradient ONE has the ability to indicates the PM2.5 levels with the LED strip using individual addressed lights and colors.  I recently switched to esphome from the default and really missed the quick indication for PM2.5 (my primary concern).  To that end, I threw together a yaml to recreate what is in the default AirGradient ONE firmware for pm2.5.  I'm no YAML expert and certainly very new to ESPHome so any efficiency suggestions or modifications would be greatly appreciated!

This could easily be recreated for CO2.  I was actually even thinking of using the first 10 LED lights for PM2.5 and then the last LED is just a color coded CO2 indicator.

Another option for further consideration would be creating a toggle (like the displays) to choose between CO2 and PM2.5 or having it split down the middle with CO2 on one side and PM2.5 on another.

At any rate, attached is the yaml I'm currently testing out for this purpose to just mimic the AirGradient ONE default firmware (I commented out the CO2 yaml from this repo for now)
[led_pm25.yaml.txt](https://github.com/MallocArray/airgradient_esphome/files/15149463/led_pm25.yaml.txt)

**Comment by ossgeek314** [comment]
I decided to add the CO2 indicator to the last LED in the chain and utilize the first 10 as PM2.5 for my current setup.  One thing that I noticed was `led_brightness` became completely useless (for whatever reason `color_brightness` doesn't actually change the brightness for the `addressable_set` idk if this is a bug in esphome or a limitation of this particular LED strip).  Because of that I added a `led_brightness` trigger to the number template so that at least the brightness would be responsive.  It does light the entire led_strip when it changes brightness but then resets itself to the guage after the interval has passed.  Anyway, I'm attaching what I did hoping maybe there is a better way.
![image](https://github.com/MallocArray/airgradient_esphome/assets/3986413/f9112309-3789-442e-84ca-356dc76cc539)

[led_co2.yaml.txt](https://github.com/MallocArray/airgradient_esphome/files/15163624/led_co2.yaml.txt)
[led_pm25.yaml.txt](https://github.com/MallocArray/airgradient_esphome/files/15163625/led_pm25.yaml.txt)
[led.yaml.txt](https://github.com/MallocArray/airgradient_esphome/files/15163626/led.yaml.txt)

**Comment by joneshf** [comment]
> for whatever reason `color_brightness` doesn't actually change the brightness for the `addressable_set` idk if this is a bug in esphome or a limitation of this particular LED strip

I'm using `color_brightness` with `light.addressable_set`, and it changes the brightness of the LEDs. So it does seem to work on this hardware. You can try looking at my setup in https://github.com/MallocArray/airgradient_esphome/issues/34#issuecomment-1972933598 and seeing if anything jumps out at you. That said, the documentation for ESPHome leaves a lot to be desired, and debugging why something happened (or didn't happen) is pretty unintuitive. it's definitely confusing to figure out!

At the moment, I'm a little too lazy to download the files to check what's going on 😅 , but I could take a look if you wanted to paste the YAML in a code block. I'll probably be less lazy later today/this week and can look at the files, if you haven't figured it out before then.

**Comment by joneshf** [comment]
I got less lazy…I don't see `color_brightness` anywhere in the files you attached, so it's a little hard to figure out what wasn't working.

I see you've got stuff like:
```YAML
light.addressable_set:
  id: led_strip
  range_from: 0
  range_to: 0
  red: 0%
  green: 100%
  blue: 0%
```
Does slapping in a `color_brightness` like this work?:
```YAML
light.addressable_set:
  color_brightness: !lambda 'return id(led_brightness).state / 100.0;'
  id: led_strip
  range_from: 0
  range_to: 0
  red: 0%
  green: 100%
  blue: 0%
```

Or was that what you already tried?

**Comment by ossgeek314** [comment]
@joneshf ,

I removed the `color_brightness` from the yaml because it seemed to not be working (and I wanted to reduce leftover testing cruft).

When I was testing it I used the following:

```
light.addressable_set:
  id: led_strip
  range_from: 0
  range_to: 0
  color_brightness: !lambda 'return id(led_brightness).state / 100.0;'
  red: 0%
  green: 100%
  blue: 0%
```
I'm wondering now if I just didn't wait 60 seconds for it to change, expecting it to be instant response.

**Comment by ossgeek314** [comment]
I just tried with the `color_brightness` attribute but was patient and allowed the minute interval to pass and it worked as expected.

Would be cool to find a way to make the response more immediate.

**Comment by ossgeek314** [comment]
I may have spoken too soon.  I setup an automation in HomeAssistant to decrease the brightness at night (25%) this seemed to completely turn off the light (but that might just be the light not able to shine through the plastic).  In the morning it automatically set the brightness to 80% but the lights have yet to come on even after a few hours.

I was able to bring the LEDs back to life by toggling the LED switch off and then on.

**Comment by MallocArray** [comment]
@DamonLane could you share your automation for HA that is doing the dimming and resuming?

I've been meaning to get back to setting up this automation as well as making the LED strip be optionally PM2.5 or CO2, as well as a combined meter as discussed here.

I don't really care for the default AirGradient behavior as I find it very unintuitive and underutilizing the strip.  I've only ever seen the 4 far right LEDs used.

I'm going to take a look at what @ossgeek314 has posted and see if I want to put my spin on it and put a PR for you all to review

**Comment by DamonLane** [comment]
I'm new to Home Assistant so this may not be the best way, but it works. I set it up in the GUI, but the yaml is probably easier to share than screenshots.

This turns my four indoor monitors' LEDs on at 7 am. Although I only set the brightness (to zero) at night, I have to switch them on, in addition to increasing their brightness for them to come back on. 

```
alias: AG LED strips on in the morning
description: ""
trigger:
  - platform: time
    at: "07:00:00"
condition: []
action:
  - service: light.turn_on
    metadata: {}
    data: {}
    target:
      entity_id:
        - light.ag_71_2_led_strip
        - light.ag_73_1_led_strip
        - light.ag_73_2_led_strip
        - light.ag_71_1_led_strip
  - service: number.set_value
    metadata: {}
    data:
      value: "40"
    target:
      entity_id:
        - number.ag_71_2_led_brightness
        - number.ag_73_1_led_brightness
        - number.ag_73_2_led_brightness
        - number.ag_71_1_led_brightness
mode: single
```

And this dims their LED strips at sunset

```
alias: Dim AG LED at sunset
description: testing 71-2
trigger:
  - platform: sun
    event: sunset
    offset: 0
condition: []
action:
  - service: light.turn_off
    target:
      entity_id:
        - light.ag_71_2_led_strip
        - light.ag_73_1_led_strip
        - light.ag_73_2_led_strip
        - light.ag_71_1_led_strip
    data: {}
mode: single
```
