### ISSUE TITLE
On-device AQI calculations

### ISSUE THREAD

**Issue by ex-nerd** [MallocArray/airgradient_esphome#46]
When I got my OpenAir, I added on-device AQI calculation to existing firmware I found. Since it resets if you power cycle, it's not as good as getting this inside of home assistant but so far I haven't found a plugin that actually does that (and I got side-tracked while working on the necessary database queries to do it myself).

The main difference with my calculations are that they are intended to more closely follow official AQI and NowCast calculations (specific differences are documented in [this commit](https://github.com/ex-nerd/ESPHome-AirGradient/commit/3c0e8db922cfb3de7950fb34aa9874739f56c95f)), which require 24 and 12 hours worth of data, respectively.

You can find the code here:

https://github.com/ex-nerd/ESPHome-AirGradient/blob/main/air-gradient-open-air.yaml

I haven't had time to poke through your code yet to figure out the best place to add it, but if someone else doesn't beat me to it, I will try to get a pull request put together to port this over. I also haven't done any work for a proper "indoor AQI" calculation, which I know includes a mix of info besides just particulate measurement.

**Comment by MallocArray** [comment]
I wonder if doing the AQI inside of HomeAssistant as a sensor template would be better, as it keeps the complex configuration out of ESPHome and lets the data reside in HA's database instead of in-memory of the ESP device, which is pretty limited, especially the ESP8266 based devices.

Looks like your code is very similar to https://github.com/ajfriesen/ESPHome-AirGradient/blob/main/air-gradient-open-air.yaml
Did you contribute similar code there?

I haven't read all the way through your code, but I see you aren't restoring the values of some of the globals, so not sure how you are tracking across a reboot, but I am trying to be cautious about the memory usage, as I've bumped up against the limit on the D1 Mini several times just with a handful of fonts.

**Comment by ex-nerd** [comment]
> Looks like your code is very similar to https://github.com/ajfriesen/ESPHome-AirGradient/blob/main/air-gradient-open-air.yaml Did you contribute similar code there?

Yes. The code in that repo is from my pull request and should be identical.

And no, it doesn't track across reboot. Based on my research at the time, the flash memory on most esp32 devices can't handle very many write cycles and would only last a few months months if anything was being written at the rate that measurements are taken. I never got around to looking into longer write cycles because at "every 6 hours (or so)" you're just getting into the realm of time it takes for the NowCast to regenerate on its own.

I agree it's something best tracked within Home Assistant, though I still haven't had time to figure that out (it gets a bit messy calculating averages when that database only stores values when they change). I'll get to it eventually (if someone else doesn't do it first) but for now, these on-device calculations work well enough.

**Comment by MallocArray** [comment]
I just pushed a package with your local nowcast and aqi calculations.  I'm still waiting for enough time for it to run the calculations, but the sensors all show up.

You could try it out by adding this under the packages section
`  nowcast_aqi: github://MallocArray/airgradient_esphome/packages/sensor_nowcast_aqi.yaml@nowcast_aqi`

**Comment by ex-nerd** [comment]
Thanks. I'll have to poke at this after work.

Over the weekend, I started looking into what it would take to get proper AQI/Nowcast calculations into home assistant, and there just doesn't seem to be a way to reliably do this with just the SQL queries or the statistics sensor (which can't look at discrete time ranges in the past, only "from now to past-time"). In the mean time, I created https://github.com/ex-nerd/home-assistant-aqi so I can eventually do the necessary expansion of "value hasn't changed" but there's a lot to learn for how to set up a plugin in general so it'll be awhile because that has anything useful.

**Comment by ex-nerd** [comment]
Oh, and just in case there is ever any doubt … the original project that contains my AQI calculation code has an MIT license, which should be compatible with this project's GPL. But I also grant separate GPL license for any of my own code that's used for this project.

**Comment by MallocArray** [comment]
I have sporadic luck with uptime in general, but not sure if it is ESPHome overall, or a specific component.
Mine has been up for 20 hours now without issue, but I have other devices that often reboot every 2 hours.

Sometime a full power cycle by removing the power cord can help.  Other times if I turn off the AirGradient Upload, or comment out the entire `airgradient_api` line it can help stabilize, but not always.


![image](https://github.com/MallocArray/airgradient_esphome/assets/9374884/f7916942-2fd2-4d08-a39b-651aae1adbb8)

**Comment by ex-nerd** [comment]
Well, yes, it would seem there's a problem with http upload. Looks like there's a workaround posted here: https://github.com/esphome/issues/issues/2853

**Comment by ex-nerd** [comment]
Just for posterity, here is the display I use in Home Assistant. It needs `card_mod`, `mini-graph-card`, `stack-in-card` extras from HACS:

```yaml
type: custom:stack-in-card
mode: vertical
keep:
  background: true
  border_radius: false
  margin: false
cards:
  - type: markdown
    content: >
      {%- set category =

      states('sensor.airgradient_open_air_nowcast_category')

      -%}

      {% if category == "unknown" %} # NowCast: Calculating

      {% set mins =
      states('sensor.airgradient_open_air_nowcast_minutes_remaining')

      | int %} Available in {% if mins > 60 %}{{ mins // 60 }} hours {% endif

      %}{{ mins%60 }} minutes

      {% else %}

      # NowCast: {{ category }}

      {% endif %}
    card_mod:
      style: |
        ha-card {
          {% set aqi = states('sensor.airgradient_open_air_nowcast') -%}
          {%- set aqi = aqi | float if is_number(aqi) else -1 -%}
          {%- if aqi < 0 -%}
            background-color: #a0a0a0; color: #393939;
          {%- elif aqi < 50 -%}
            background-color: #00e400; color: #393939;
          {%- elif aqi < 100 -%}
            background-color: #ffff00; color: #004000;
          {%- elif aqi < 150 -%}
            background-color: #ff7e00; color: #404000;
          {%- elif aqi < 200 -%}
            background-color: #ff0000; color: #400000;
          {%- elif aqi < 300 -%}
              background-color: #8f3f97; color: #300030;
          {%- else -%}
            background-color: #7e0023; color: #200000;
          {% endif %}
          text-align: center;
        }
        h1 {
          line-height: 1px;
          margin: 0 !important;
          padding: 0 !important;
          border: 1px solid red !impotant;
        }
  - type: conditional
    conditions:
      - entity: sensor.airgradient_open_air_nowcast
        state_not: unknown
    card:
      type: gauge
      entity: sensor.airgradient_open_air_nowcast
      needle: true
      min: 0
      max: 500
      segments:
        - from: 0
          color: '#00e400'
        - from: 50
          color: '#ffff00'
        - from: 100
          color: '#ff7e00'
        - from: 150
          color: '#ff0000'
        - from: 200
          color: '#8f3f97'
        - from: 300
          color: '#7e0023'
      name: ''
  - type: custom:mini-graph-card
    entities:
      - entity: sensor.airgradient_open_air_nowcast
    color_thresholds:
      - value: 0
        color: '#00e400'
      - value: 50
        color: '#ffff00'
      - value: 100
        color: '#ff0000'
      - value: 200
        color: '#8f3f97'
      - value: 300
        color: '#7e0023'
    show:
      labels: false
      fill: fade
      name: false
      state: true
      icon: false
    min_bound_range: 20
    line_width: 4
    hours_to_show: 24
    points_per_hour: 1
    card_mod:
      style: |
        div.states {
          display: none !important;
          position: absolute;
          bottom: 0;
          left: 0;
        }
        ha-card:hover div.states {
          display:block !important;
        }
  - type: markdown
    content: |
      {%- set category =
      states('sensor.airgradient_open_air_aqi_category')
      -%} {% if category == "unknown" %} # AQI: Calculating

      {% set mins = states('sensor.airgradient_open_air_aqi_minutes_remaining')
      | int %} Available in {% if mins > 60 %}{{ mins // 60 }} hours {% endif
      %}{{ mins%60 }} minutes
      {% else %} # AQI: {{ category }} {% endif %}
    card_mod:
      style: |
        ha-card {
          {% set aqi = states('sensor.airgradient_open_air_aqi') -%}
          {%- set aqi = aqi | float if is_number(aqi) else -1 -%}
          {%- if aqi < 0 -%}
            background-color: #a0a0a0; color: #393939;
          {%- elif aqi < 50 -%}
            background-color: #00e400; color: #393939;
          {%- elif aqi < 100 -%}
            background-color: #ffff00; color: #004000;
          {%- elif aqi < 150 -%}
            background-color: #ff7e00; color: #404000;
          {%- elif aqi < 200 -%}
            background-color: #ff0000; color: #400000;
          {%- elif aqi < 300 -%}
              background-color: #8f3f97; color: #300030;
          {%- else -%}
            background-color: #7e0023; color: #200000;
          {% endif %}
          text-align: center;
        }
        h1 {
          line-height: 1px;
          margin: 0 !important;
          padding: 0 !important;
          border: 1px solid red !impotant;
        }
  - type: conditional
    conditions:
      - entity: sensor.airgradient_open_air_aqi
        state_not: unknown
    card:
      type: gauge
      entity: sensor.airgradient_open_air_aqi
      needle: true
      min: 0
      max: 500
      segments:
        - from: 0
          color: '#00e400'
        - from: 50
          color: '#ffff00'
        - from: 100
          color: '#ff7e00'
        - from: 150
          color: '#ff0000'
        - from: 200
          color: '#8f3f97'
        - from: 300
          color: '#7e0023'
      name: ''
  - type: custom:mini-graph-card
    entities:
      - entity: sensor.airgradient_open_air_aqi
    color_thresholds:
      - value: 0
        color: '#00e400'
      - value: 50
        color: '#ffff00'
      - value: 100
        color: '#ff0000'
      - value: 200
        color: '#8f3f97'
      - value: 300
        color: '#7e0023'
    show:
      labels: false
      fill: fade
      name: false
      state: true
      icon: false
    min_bound_range: 20
    line_width: 4
    hours_to_show: 72
    points_per_hour: 0.125
    card_mod:
      style: |
        div.states {
          display: none !important;
          position: absolute;
          bottom: 0;
          left: 0;
        }
        ha-card:hover div.states {
          display:block !important;
        }
  - type: horizontal-stack
    cards:
      - type: custom:mini-graph-card
        entities:
          - entity: sensor.airgradient_open_air_pm_1_0_average
            name: PM1
            state_adaptive_color: true
            color: wheat
        line_width: 2
        hours_to_show: 24
        min_bound_range: 10
        show:
          labels: false
          fill: fade
          name: true
          icon: false
          name_adaptive_color: true
      - type: custom:mini-graph-card
        entities:
          - entity: sensor.airgradient_open_air_pm_2_5_average
            name: PM2.5
            state_adaptive_color: true
            color: tan
        line_width: 2
        hours_to_show: 24
        min_bound_range: 10
        show:
          labels: false
          fill: fade
          name: true
          icon: false
          name_adaptive_color: true
      - type: custom:mini-graph-card
        entities:
          - entity: >-
              sensor.airgradient_open_air_pm_10_0_average
            name: PM10
            state_adaptive_color: true
            color: burlywood
        line_width: 2
        hours_to_show: 24
        min_bound_range: 10
        show:
          labels: false
          fill: fade
          name: true
          icon: false
          name_adaptive_color: true
columns: 1
```

**Comment by MallocArray** [comment]
Looking again, I see the "PM 2.5 1h Average" has a siliding window moving average that assumes the update_interval of the PMS5003 sensor is 3 minutes as you had it.  I'm currently using the ESPHome default which is whenever a value comes in, 1 second with this hardware.
There is an alternative file that has a 2 min interval configured.  There is some concern that allowing the fan to shut down outdoors could let insects get inside or that accuracy on the first reading after spinup may not be fully accurate, so I don't want to hard code the default to 3 min.

Not sure what is best to do with the 1h average.  Leaving it as you had it wouldn't be a true 1 hr average if readings are coming in every second, but I don't think you can use a substitution for the window_size, or not with a calculation.

Thoughts?

**Comment by ex-nerd** [comment]
> There is an alternative file that has a 2 min interval configured. There is some concern that allowing the fan to shut down outdoors could let insects get inside or that accuracy on the first reading after spinup may not be fully accurate, so I don't want to hard code the default to 3 min.

I wondered why the default was set to 1s when everything in the forums when I bought mine said to use the delayed values (especially with something like AQI that's intended to only change once/day, or nowCast once/hour). 

I think I added the [`pm_update_interval` substitution](https://github.com/ex-nerd/ESPHome-AirGradient/blob/main/air-gradient-open-air.yaml) to my original updates for this to account for that. Would it work to just add something like that to each of the two PMS5003 files? If not, maybe a global/variable would work.

**Comment by ex-nerd** [comment]
> Not sure what is best to do with the 1h average. Leaving it as you had it wouldn't be a true 1 hr average if readings are coming in every second, but I don't think you can use a substitution for the window_size, or not with a calculation.

Looking at the code again, I wonder if the better option would be to replace the "copy" sensor with a template that runs on a schedule and just reads the current value of the sensor? Something like:

```yaml
  - platform: template
    id: pm_2_5_1h_avg
    name: "PM 2.5 1h Average"
    disabled_by_default: true
    device_class: pm25
    accuracy_decimals: 1
    filters:
      - sliding_window_moving_average:
          window_size: 60
          send_every: 60
          send_first_at: 60
    update_interval: 60s
    lambda: |
      return id(pm_2_5_1h_avg).state;
    on_value:
      lambda: |
        // Insert the current value
        float current = id(pm_2_5_1h_avg).state;
        if (!isnan(current)) {
          id(pm_2_5_hourly_avg).insert(id(pm_2_5_hourly_avg).begin(), current);
          // Truncate anything past the first 24
          if (id(pm_2_5_hourly_avg).size() > 24) {
            id(pm_2_5_hourly_avg).resize(24);
          }
        }
```
