### ISSUE TITLE
Rotate Display

### ISSUE THREAD

**Issue by DariBer** [MallocArray/airgradient_esphome#49]
I wonder if there is anyway to rotate the display?

**Comment by MallocArray** [comment]
Yes, you can add this to your main top-level YAML file.  It will add to the existing package configuration to rotate the display.  I put it at the very bottom of my file.

```yaml
display:
  - id: !extend oled_display
    rotation: 180°
```
