### ISSUE TITLE
Airgradient One (v9) LEDs Keep Turning Back On

### ISSUE THREAD

**Issue by msirianni** [MallocArray/airgradient_esphome#8]
Flashed a new pre-assembled kit with ESPHome via your YAML and it is mostly working, but when I turn off the LED strip via HA it initially works, but then turns itself back on a few seconds later. This repeats every time I turn it off via HomeAssistant. 

Separately, it seems the LEDs are all constantly on and only Green no matter the detected AQI. Is there a way to restore the behavior of the stock LEDs where they move from left to right and change color to match AQI conditions? 

Thanks!

**Comment by MallocArray** [comment]
The LEDs always being on is a current limitation, as each time the CO2 sensor gets a value it turns the lights back on to the appropriate value.

When I first got my V9 kit, the LEDs were associated with the CO2 values. It will be green until it goes over 800 then start going orange, red, purple, etc.

I am in the middle of updating this so the brightness can be set in HA and will be persistent so you can make it dimmer or off entirely.

If AirGradient changed the LED to reflect the AQI, that would take a bit more work to add a config for, but could be done.  I don't think the AQI values are that accurate for indoor, so it is a lower priority for me right now.

I'm maybe a day away from some new BIN files and hopefully I'll have the yaml files ready to share at that point as well.  I still have the outdoor monitor to test with my updates.  I'll let you know.

**Comment by MallocArray** [comment]
I just uploaded the latest .bin files to the main branch if you want to manually upload the latest.

In the `includes` branch, I've started splitting out the different components so I can refer to one file across different models without having to maintain the configs individually.  It may be a bit confusing while I finish working on it and come up with some resulting files that have all of the separate ones combined into standalone files, but that will come later.

**Comment by strikeir13** [comment]
As a temporary measure, I adjusted the One V9 esphome config so that my Home Assistant input boolean 'Quiet Hours' will override the LED updates and keep the LEDs off when I turn them off at night. Here's all I changed:

Pulled in the Home Assistant input boolean entity:
```
text_sensor:
  - platform: homeassistant
    name: "Quiet Hours - Home Assistant"
    id: quiethours
    entity_id: input_boolean.quiet_hours
```

Added a check on the above sensor within each of the CO2 condition lambdas, like this:
```
      on_value:
        - if:
            condition:
                lambda: 'return id(co2).state < 800 && !id(quiethours).state;'
            then:
              - light.turn_on:
                  id: led_strip
                  brightness: 100%
                  red: 0%
                  green: 100%
                  blue: 0%
        - if:
            condition:
                lambda: 'return id(co2).state >= 800 && id(co2).state < 1000 && !id(quiethours).state;'
            then:
              - light.turn_on:
                  id: led_strip
                  brightness: 100%
                  red: 100%
                  green: 100%
                  blue: 0%
```

Just make sure to add the `&& !id(quiethours).state` section to each CO2 condition lambda. After these changes, you can turn on the Quiet Hours switch in Home Assistant, turn off the Airgradient LED strip, and it will stay off until you turn off Quiet Hours. At that point, it will turn the lights on at the next sensor update.
